= JSON

_JSON_ is a the acronym of *JavaScript Object Notation*.
It is used primarly to transmit data between a server and a web application as an alternative to _XML_.

== Data types

_JSON's_ basic types are:

Number:: Signed decimal number with optional fractional and exponential part.
String:: *Unicode* characters.
Boolean:: `true` or `false`.
Array:: Ordered list of elements in array form.
Object:: Unordered associative array of name/value pairs delimited with curly brackets ('`{`') and ('`}`') and each pair separated by colon ('`:`') character.
Null:: `null`.

== Example

[source, json]
----
{
    "firstName": "John", //<1>
    "lastName": "Smith",
    "isAlive": true, //<2>
    "age": 25,
    "heightCm": 167.6, //<3>
    "address": { //<4>
        "streetAddress": "21 2nd Street",
        "city": "New York",
        "state": "NY",
        "postalCode": "10021-3100"
    },
    "phoneNumbers": [ //<5>
        {
            "type": "home",
            "number": "212 555-1234"
        },
        {
            "type": "office",
            "number": "646 555-4567"
        }
    ],
    "favoriteColors": ["blue", "yellow"], //<6>
    "spouse": null //<7>
}
----
<1> Attribute with string value.
<2> Attribute with boolean value. Note that it is not quoted ('`"`').
<3> Attribute with decimal value and fraction.
<4> Definition of object with several attributes divided by comma ('`,`').
<5> Arrays are defined between brackets ('`[`') and ('`]`'), and each element separated by comma ('`,`'). Note that an array may contain objects too.
<6> Arrays may contain native types.
<7> null attribute value.

== Best Practices

* Indent in _JSON_ documents must be two or four white spaces.
* Only one key/value pair per line.
* In case of objects, opening curly bracket should be placed after colon, and closing curly bracket at same idention level as key.
* In case of arrays of objects, opening bracket should be placed after colon, and closing bracket at same idention level as key.
* Arrays of simple types may be defined in a single line.
* Attribute names must follow camel case notation with lowercase first letter.
